version: '3'
services:
    sonar:
        build: ./sonar
    api:
        build: ./api
        volumes:
            - './api/app:/usr/local/src/skiff/app/api/app'
            - './api/requirements.txt:/usr/local/src/skiff/app/api/requirements.txt'
        environment:
            # This ensures that errors are printed as they occur, which
            # makes debugging easier.
            - 'PYTHONUNBUFFERED=1'
            - 'LOG_LEVEL=DEBUG'
            - 'SUPP_AI_ALGOLIA_API_KEY=${SUPP_AI_ALGOLIA_API_KEY}'
            - 'SUPP_AI_CANONICAL_ORIGIN=http://localhost:8080'
    ui:
        build: ./ui
        # We can't mount the entire UI directory, since the `node_modules`
        # by default live at that location. Instead we mount the specific
        # collection of files that should propagate from the host to the
        # container.
        volumes:
            - './ui/src:/usr/local/src/skiff/app/ui/src'
            - './ui/public:/usr/local/src/skiff/app/ui/public'
            - './ui/package.json:/usr/local/src/skiff/app/ui/package.json'
            - './ui/tsconfig.json:/usr/local/src/skiff/app/ui/tsconfig.json'
            - './ui/next.config.js:/usr/local/src/skiff/app/ui/next.config.js'
            - './ui/yarn.lock:/usr/local/src/skiff/app/ui/yarn.lock'
            - './ui/.babelrc:/usr/local/src/skiff/app/ui/.babelrc'
            - './ui/pages:/usr/local/src/skiff/app/ui/pages'
            - './ui/api:/usr/local/src/skiff/app/ui/api'
            - './ui/util:/usr/local/src/skiff/app/ui/util'
            - './ui/components:/usr/local/src/skiff/app/ui/components'
            - './ui/@types:/usr/local/src/skiff/app/ui/@types'
        command:
            - 'dev'
        environment:
            - 'SUPP_AI_CANONICAL_ORIGIN=http://localhost:8080'
    proxy:
        build: ./proxy
        ports:
            - '8080:80'
        depends_on:
            - ui
            - api
